/* Copyright (c) 2026 Celia. All rights reserved. */
import {useEffect,useMemo,useRef,useState} from 'react';
import {LockKeyhole,RotateCcw,Unlock} from 'lucide-react';
import ChessBoard from './ChessBoard';
import ChessMatch from './ChessMatch';
import {DEFAULT_POSITION,readBoard,setupFen,setupIssues,pieceNames,glyphs,replay,researchTargets,opposite,sideName,type Color,type GameState,type PieceSymbol,type Square,type Token} from './engine';
export default function ChessTeaching({active}:{active:boolean}){
 const [pieces,setPieces]=useState(()=>readBoard(DEFAULT_POSITION)),[turn,setTurn]=useState<Color>('w'),[human,setHuman]=useState<Color>('w');
 const [selected,setSelected]=useState<Square|null>(null),[placing,setPlacing]=useState<{color:Color;type:PieceSymbol}|null>(null),[locked,setLocked]=useState(false),[research,setResearch]=useState(false),[confirming,setConfirming]=useState(false),[message,setMessage]=useState('点击棋子再点空格移动；也可以从备用区选一枚棋子放入棋盘。');
 const [state,setState]=useState<GameState>({start:DEFAULT_POSITION,line:[]}),dialog=useRef<HTMLDialogElement>(null),issues=useMemo(()=>setupIssues(pieces,turn),[pieces,turn]);
 const current=pieces.find(p=>p.square===selected),fen=setupFen(pieces,turn),legal=current?(research?researchTargets(pieces,current):Array.from({length:64},(_,i)=>(String.fromCharCode(97+i%8)+(8-Math.floor(i/8))) as Square).filter(s=>!pieces.some(p=>p.square===s))):[];
 useEffect(()=>{if(confirming&&active)dialog.current?.showModal();else dialog.current?.close();},[confirming,active]);
 function researchMove(p:Token,to:Square){setPieces(s=>s.filter(q=>q.square!==to).map(q=>q.square===p.square?{...q,square:to,type:q.type==='p'&&/[18]$/.test(to)?'q':q.type}:q));setSelected(null);setTurn(t=>opposite(t));setMessage('研究落子完成，不判断正常胜负。兵到底线时在此研究模式自动变为后。');}
 useEffect(()=>{if(!active||!locked||!research||turn===human)return;const choices=pieces.filter(p=>p.color===turn).flatMap(p=>researchTargets(pieces,p).map(to=>({p,to}))).sort((a,b)=>Number(pieces.some(p=>p.square===b.to))-Number(pieces.some(p=>p.square===a.to)));if(!choices.length){setMessage('对方没有基本走法，请解锁调整棋子。');return;}const timer=setTimeout(()=>researchMove(choices[0].p,choices[0].to),650);return()=>clearTimeout(timer);},[pieces,turn,locked,research,active,human]);
 function click(square:Square){const target=pieces.find(p=>p.square===square);
  if(locked){if(turn!==human){setMessage('对方正在演示走法，请稍等。');return;}if(target?.color===human){setSelected(selected===square?null:square);return;}if(current&&legal.includes(square))researchMove(current,square);else setMessage('请选择本方棋子，再点击它的基本走法落点。');return;}
  if(placing){if(target){setMessage('这里已有棋子，请换一个空格。');return;}setPieces(s=>[...s,{...placing,square}]);setPlacing(null);setSelected(null);return;}
  if(target){setSelected(selected===square?null:square);return;}if(selected){setPieces(s=>s.map(p=>p.square===selected?{...p,square}:p));setSelected(null);}
 }
 function restore(){setConfirming(false);setLocked(false);setResearch(false);setPieces(readBoard(DEFAULT_POSITION));setTurn('w');setSelected(null);setPlacing(null);setMessage('已恢复标准棋子摆放。自由摆局默认不授予王车易位和吃过路兵权利。');}
 function start(asResearch=false){setConfirming(false);setSelected(null);setPlacing(null);setResearch(asResearch);if(!asResearch)setState({start:fen,line:[]});setLocked(true);setMessage('已保留原局面，按基本走法进行非标准研究。');}
 if(locked&&!research)return <ChessMatch active={active} state={state} setState={setState} mode="ai" setMode={()=>{}} human={human} onUnlock={()=>{const g=replay(state);setPieces(readBoard(g.fen()));setTurn(g.turn());setLocked(false);setSelected(null);setMessage('已保留对弈后的局面，可以继续自由摆放。');}}/>;
 return <><div className="play-layout chess-play-layout"><section className="game-panel"><div className="game-heading"><strong>{locked?'非标准研究 · 我执'+sideName(human):'自由摆局 · 双方可调整'}</strong><span>{sideName(turn)}先行 / 当前行棋</span></div>{research&&<p className="research-banner">仅按基本走法研究，不校验王的安全，不判胜负；不演示易位和吃过路兵。</p>}<ChessBoard fen={fen} selected={selected} legal={legal} onSquare={click}/><p className="teaching-message" role="status">{message}</p><button className="outline" onClick={restore}><RotateCcw size={16}/>恢复标准摆放</button></section>
 <aside className="play-info"><div className="info-card"><h3><LockKeyhole size={18}/> 摆好，再锁定</h3><div className="teaching-selects"><label>我执哪方<select disabled={locked} value={human} onChange={e=>setHuman(e.target.value as Color)}><option value="w">白方</option><option value="b">黑方</option></select></label><label>谁先走<select disabled={locked} value={turn} onChange={e=>setTurn(e.target.value as Color)}><option value="w">白方</option><option value="b">黑方</option></select></label></div>
 <button className="primary full" onClick={()=>{if(locked){setLocked(false);setResearch(false);return;}if(issues.length)setConfirming(true);else start();}}>{locked?<><Unlock size={16}/>解锁，继续摆局</>:<>锁定并开始对弈<LockKeyhole size={16}/></>}</button>
 {!locked&&<><p>自由摆局默认双方无王车易位权，也没有可吃的过路兵。锁定后按普通规则下棋。</p><button className="outline full" disabled={!selected} onClick={()=>{setPieces(s=>s.filter(p=>p.square!==selected));setSelected(null);}}>移出选中棋子</button><div className="chess-reserve">{(['w','b'] as Color[]).map(color=><div key={color}><span>{sideName(color)}备用棋子</span><div>{(['k','q','r','b','n','p'] as PieceSymbol[]).map(type=><button key={type} className={placing?.color===color&&placing.type===type?'chosen':''} aria-label={`放入${sideName(color)}${pieceNames[type]}`} onClick={()=>{setPlacing(placing?.color===color&&placing.type===type?null:{color,type});setSelected(null);}}>{glyphs[type]}</button>)}</div></div>)}</div>{issues.length>0&&<p className="position-warning">发现 {issues.length} 项问题：{issues[0]}</p>}</>}</div><div className="info-card"><h3>摆局小提示</h3><p>可以从完整开局移除棋子，也可以调整位置，研究车、马、象、后的配合。</p><p>正常局面锁定后，每一步都会分析推荐走法和用途。不合理局面可以恢复、返回调整，或继续非标准研究。</p><small>检查基础规则与明显冲突，不证明每个摆局都能从标准开局实际走出。</small></div></aside></div>
 <dialog ref={dialog} className="position-dialog" aria-labelledby="chess-position-title" onCancel={()=>setConfirming(false)}><h2 id="chess-position-title">棋局不合理</h2><p>这个局面不适合直接进入正常对弈：</p><ul>{issues.map(i=><li key={i}>{i}</li>)}</ul><p className="research-banner">仍然开始会保留原摆局，进入不校验王安全、不判胜负的基础走法研究。</p><div className="dialog-actions"><button className="primary" onClick={restore}>恢复标准摆放</button><button className="outline" onClick={()=>start(true)}>仍然开始研究</button><button className="text-button" autoFocus onClick={()=>setConfirming(false)}>返回调整</button></div></dialog></>;
}
