/* Copyright (c) 2026 Celia. All rights reserved. */
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Lightbulb,RotateCcw} from 'lucide-react';
import ChessBoard from './ChessBoard';
import {Chess,replay,label,illegalExplanation,type GameState,type InputMove,type Square} from './engine';
import {chessPuzzles,type ChessPuzzle} from './data';
function Puzzle({p,active,onDone}:{p:ChessPuzzle;active:boolean;onDone:()=>void}){
 const [state,setState]=useState<GameState>({start:p.fen,line:[]}),[selected,setSelected]=useState<Square|null>(null),[done,setDone]=useState(false),[hint,setHint]=useState(false),[answer,setAnswer]=useState(false),[cursor,setCursor]=useState(0),[message,setMessage]=useState('白方先行，尝试走出本题的目标。');
 const game=useMemo(()=>replay(state),[state]),ply=state.line.length,legal=selected?game.moves({square:selected,verbose:true}).map(m=>m.to):[],history=game.history({verbose:true});
 const solution=useMemo(()=>{const g=new Chess(p.fen),fens=[p.fen],labels:string[]=[];for(const m of p.line){labels.push(label(g.move(m)));fens.push(g.fen());}return {fens,labels};},[p]);
 useEffect(()=>{if(!active||answer||done||game.turn()!=='b'||!p.line[ply])return;const timer=setTimeout(()=>{setState(s=>({...s,line:[...s.line,p.line[ply]]}));setMessage(p.line[ply].why);},650);return()=>clearTimeout(timer);},[ply,active,answer,done,p]);
 function square(to:Square){if(done||answer||game.turn()==='b')return;const piece=game.get(to);if(piece?.color==='w'){setSelected(selected===to?null:to);return;}if(!selected){setMessage('请先选择白方棋子。');return;}if(!legal.includes(to)){setMessage(illegalExplanation(game,selected,to));return;}
  const m:InputMove={from:selected,to},next=new Chess(game.fen());try{next.move(m);}catch{setMessage('请选择参考路线中的走法。');return;}const expected=p.line[ply],matches=expected?.from===m.from&&expected.to===m.to,alternative=p.goal==='mate'?next.isCheckmate():p.goal==='escape'?!next.isAttacked(next.board().flat().find(p=>p?.color==='w'&&p.type==='k')!.square,'b'):false;
  if(!matches&&!alternative){setMessage('这是合法走法，但没有完成本题的参考目标。题面已保留，可以继续试或查看答案。');return;}setState(s=>({...s,line:[...s.line,m]}));setSelected(null);setMessage(matches?expected.why:'这也是达成目标的有效走法。');if(alternative||ply===p.line.length-1){setDone(true);onDone();}
 }
 function reset(){setState({start:p.fen,line:[]});setDone(false);setAnswer(false);setCursor(0);setHint(false);setSelected(null);setMessage('已恢复题面，白方先行。');}
 return <div className="play-layout chess-play-layout"><section className="game-panel"><div className="game-heading"><strong>{p.name}</strong><span>{answer?'答案演示':done?'练习完成':game.turn()==='w'?'白方行棋':'黑方应手中'}</span></div><ChessBoard fen={answer?solution.fens[cursor]:game.fen()} selected={answer?null:selected} legal={answer?[]:legal} last={answer?(cursor?p.line[cursor-1]:undefined):history[history.length-1]} recommendation={answer?p.line[cursor]:hint?p.line[ply]:undefined} onSquare={answer?undefined:square}/>
 {answer?<div className="review-controls"><button className="outline" disabled={!cursor} onClick={()=>setCursor(c=>c-1)}><ArrowLeft size={16}/>上一步</button><span>{cursor} / {p.line.length}</span><button className="outline" disabled={cursor===p.line.length} onClick={()=>setCursor(c=>c+1)}>下一步<ArrowRight size={16}/></button></div>:<div className="board-toolbar"><button onClick={()=>setHint(s=>!s)}><Lightbulb size={16}/>提示</button><button onClick={reset}><RotateCcw size={16}/>重试</button></div>}
 <p className="teaching-message" role="status">{answer?(cursor?p.line[cursor-1].why:'这是题目初始局面。点击下一步逐步学习。'):(done?'练习完成！':'')+message}</p></section><aside className="play-info"><div className="info-card"><h3>本题目标</h3><p>{p.goal==='mate'?'完成将死':p.goal==='gain'?'利用将军得车':p.goal==='pin'?'让车牵制黑马':'解除对白王的将军'} · 白方 {Math.ceil(p.line.length/2)} 手参考路线</p>{hint&&<p className="idiom">{p.hint}</p>}<button className="primary full" onClick={()=>{setAnswer(s=>!s);setCursor(0);}}><BookOpen size={16}/>{answer?'回到我的练习':'查看答案与逐步解析'}</button>{answer?<ol className="solution-list">{p.line.map((m,i)=><li key={i}><button className={cursor===i+1?'active':''} onClick={()=>setCursor(i+1)}><strong>{solution.labels[i]}</strong><span>{m.why}</span></button></li>)}</ol>:<p>多步题自动演示黑方的一条合法应对。走错会保留题面；答案演示不会计作完成。</p>}</div></aside></div>;
}
export default function ChessPuzzles({active}:{active:boolean}){const [chosen,setChosen]=useState(0),[attempt,setAttempt]=useState(0),[solved,setSolved]=useState<number[]>([]);return <><Puzzle key={chosen+'-'+attempt} p={chessPuzzles[chosen]} active={active} onDone={()=>setSolved(s=>s.includes(chosen)?s:[...s,chosen])}/><section className="puzzle-library"><div className="library-heading"><h2>国际棋谱小藏</h2><span>已练习 {solved.length} / {chessPuzzles.length}</span></div><div className="challenge-grid">{chessPuzzles.map((p,i)=><button className={'challenge-card '+(i===chosen?'current':'')} key={p.id} onClick={()=>{setChosen(i);setAttempt(n=>n+1);window.scrollTo({top:0,behavior:'smooth'});}}><span className="small-label">第 {String(i+1).padStart(2,'0')} 关 · {Math.ceil(p.line.length/2)} 手</span><h3>{p.name}</h3><span className="challenge-action">{solved.includes(i)?'已练习，再来一次':'开始练习'}<ArrowRight size={15}/></span></button>)}</div><p className="analysis-note">题目与解析独立编排，参考路线已按国际象棋规则校验。此处为入门训练集，不是完整残局数据库。</p></section></>;}
