/* Copyright (c) 2026 Celia. All rights reserved. */
import {useEffect,useMemo,useRef,useState,type Dispatch,type SetStateAction} from 'react';
import {ArrowRight,History,Lightbulb,RotateCcw,Undo2,Unlock} from 'lucide-react';
import ChessBoard from './ChessBoard';
import {replay,sideName,label,outcome,explainMove,illegalExplanation,pieceNames,glyphs,type Advice,type Color,type GameState,type InputMove,type PieceSymbol,type Square} from './engine';
export function useAdvice(fen:string,enabled:boolean,state?:GameState){const [advice,setAdvice]=useState<Advice|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);const positionKey=state?JSON.stringify(state):fen;useEffect(()=>{setAdvice(null);setError('');if(!enabled){setBusy(false);return;}setBusy(true);const worker=new Worker(new URL('./analysis.worker.ts',import.meta.url),{type:'module'});worker.onmessage=({data})=>{setBusy(false);setAdvice(data.advice??null);setError(data.error??'');};worker.onerror=()=>{setBusy(false);setError('分析暂时失败，请重试。');};worker.postMessage({fen,state});return()=>worker.terminate();},[positionKey,enabled,retry]);return {advice,busy,error,retry:()=>setRetry(x=>x+1)};}
type Props={state:GameState;setState:Dispatch<SetStateAction<GameState>>;active:boolean;mode:'ai'|'local';setMode:(m:'ai'|'local')=>void;human?:Color;onReview?:()=>void;onUnlock?:()=>void};
export default function ChessMatch({state,setState,active,mode,setMode,human='w',onReview,onUnlock}:Props){
 const game=useMemo(()=>replay(state),[state]),fen=game.fen(),history=game.history({verbose:true}),last=history[history.length-1],end=outcome(game);
 const [selected,setSelected]=useState<Square|null>(null),[message,setMessage]=useState('白方先行。点击棋子，再点绿色落点。'),[hint,setHint]=useState(false),[promotion,setPromotion]=useState<InputMove|null>(null);
 const dialog=useRef<HTMLDialogElement>(null),analysis=useAdvice(fen,active&&!end,state),legal=selected?game.moves({square:selected,verbose:true}):[];
 useEffect(()=>{if(promotion&&active)dialog.current?.showModal();else dialog.current?.close();},[promotion,active]);
 function commit(m:InputMove){try{const move=replay(state).move(m);setState(s=>({...s,line:[...s.line,{from:move.from,to:move.to,promotion:move.promotion}]}));setSelected(null);setHint(false);setPromotion(null);setMessage(explainMove(move));}catch{setMessage('这步不能走，请重新选择合法落点。');}}
 useEffect(()=>{if(!active||mode!=='ai'||game.turn()===human||end||!analysis.advice?.move)return;const timer=setTimeout(()=>commit(analysis.advice!.move!),500);return()=>clearTimeout(timer);},[fen,analysis.advice,mode,active,human,end]);
 function square(s:Square){if(end){setMessage(end);return;}if(mode==='ai'&&game.turn()!==human){setMessage('对方正在思考，请稍等。');return;}const p=game.get(s);if(p?.color===game.turn()){setSelected(selected===s?null:s);setHint(false);return;}if(!selected){setMessage('请先选择'+sideName(game.turn())+'的棋子。');return;}const options=legal.filter(m=>m.to===s);if(!options.length){setMessage(illegalExplanation(game,selected,s));return;}const input={from:selected,to:s};if(options.some(m=>m.promotion))setPromotion(input);else commit(input);}
 function reset(){setState(s=>({...s,line:[]}));setPromotion(null);setSelected(null);setHint(false);setMessage('已恢复本局起点。白方执棋时从下方向上走兵。');}
 return <><div className="play-layout chess-play-layout"><section className="game-panel"><div className="game-heading"><strong>{onUnlock?'锁定教学':'国际象棋 · '+(mode==='ai'?'新手陪练':'本地双人')}</strong><span>{end?'本局结束':`${sideName(game.turn())}行棋${game.isCheck()?' · 被将军':''}`}</span></div>
 <ChessBoard fen={fen} selected={selected} legal={legal.map(m=>m.to)} last={last} recommendation={onUnlock||hint?analysis.advice?.move:undefined} onSquare={square} flipped={human==='b'&&mode==='ai'}/>
 <div className="board-toolbar"><button disabled={!state.line.length} onClick={()=>{const count=mode==='ai'&&game.turn()===human?2:1;setState(s=>({...s,line:s.line.slice(0,Math.max(0,s.line.length-count))}));setSelected(null);setPromotion(null);setMessage('已撤回，再看一看其他选择。');}}><Undo2 size={16}/>悔棋</button><button disabled={!!end||analysis.busy||mode==='ai'&&game.turn()!==human||!analysis.advice?.move} onClick={()=>{setHint(true);setSelected(analysis.advice!.move!.from);setMessage(analysis.advice!.title+'。'+analysis.advice!.purpose);}}><Lightbulb size={16}/>提示</button><button onClick={reset}><RotateCcw size={16}/>重开</button></div><p className="teaching-message" role="status">{end||message}</p><p className="board-legend">绿色：合法落点 · 金框：推荐位置 · 国际象棋的马可以跳子，兵直进斜吃。</p></section>
 <aside className="play-info"><div className="info-card"><h3>{onUnlock?'锁定一方 · 边下边懂':'这一局，慢慢来'}</h3>{onUnlock?<><p>你执{sideName(human)}，对方由本地 AI 应战。</p><button className="outline full" onClick={onUnlock}><Unlock size={16}/>解锁，继续摆局</button></>:<div className="mode-options"><button className={mode==='ai'?'chosen':''} onClick={()=>setMode('ai')}>AI 陪练 · 我执白</button><button className={mode==='local'?'chosen':''} onClick={()=>setMode('local')}>本地双人</button></div>}
 <div className="chess-analysis" aria-live="polite"><h4>这一手的思路</h4>{analysis.busy?<p>正在比较双方的合法走法…</p>:analysis.error?<><p>{analysis.error}</p><button className="outline" onClick={analysis.retry}>重新分析</button></>:analysis.advice?<><strong>{analysis.advice.title}</strong><p>{analysis.advice.why}</p><p>{analysis.advice.purpose}</p>{analysis.advice.idiom&&<p className="chess-idiom">{analysis.advice.idiom}<small>帮助理解的成语比喻</small></p>}<small>本地搜索 {analysis.advice.depth} 层 · 练习难度，有限搜索不保证最佳。</small></>:<p>{end||'走一步，看看下一步的思路。'}</p>}</div>
 <p className="analysis-note">本练习将三次重复与五十回合条件自动判和；不提供比赛中的申请和棋及裁判流程。</p></div>
 <div className="info-card"><h3>落子记录 <small>{state.line.length} 手</small></h3><ol className="move-list chess-moves">{history.map((m,i)=><li key={i}>{label(m)} <span>{m.san}</span></li>)}</ol>{!history.length&&<p>棋盘已备好，白方先行。</p>}{onReview&&<button className="outline full" onClick={onReview}>回看这一局 <History size={16}/></button>}</div></aside></div>
 <dialog ref={dialog} className="position-dialog" aria-labelledby="promotion-title" onCancel={()=>setPromotion(null)}><h2 id="promotion-title">兵到底线了，选择升变</h2><p>可以选择后、车、象或马。通常后最强，也有需要升变为马的局面。</p><div className="promotion-options">{(['q','r','b','n'] as PieceSymbol[]).map(t=><button key={t} onClick={()=>promotion&&commit({...promotion,promotion:t})}><span>{glyphs[t]}</span>升变为{pieceNames[t]}</button>)}</div><button className="text-button" onClick={()=>setPromotion(null)}>返回，重新考虑</button></dialog></>;
}
