/* Copyright (c) 2026 Celia. All rights reserved. */
import {useEffect,useState} from 'react';
import {ArrowLeftRight,ArrowRight,BookOpen,Flag,History,House,Lightbulb,Menu,Swords,Volume2,VolumeX,X} from 'lucide-react';
import InstallApp from '../components/InstallApp';
import {chessSound,setSoundEnabled} from '../game/sound';
import ChessBoard from './ChessBoard';
import ChessMatch from './ChessMatch';
import ChessTeaching from './ChessTeaching';
import ChessLearn from './ChessLearn';
import ChessReview from './ChessReview';
import ChessPuzzles from './ChessPuzzles';
import {DEFAULT_POSITION,type GameState} from './engine';
import './chess.css';
const nav=[{id:'home',label:'棋院首页',icon:House},{id:'play',label:'国际象棋对局',icon:Swords},{id:'learn',label:'入门教学',icon:BookOpen},{id:'teaching',label:'教学棋局',icon:Lightbulb},{id:'puzzles',label:'残局闯关',icon:Flag},{id:'review',label:'对局复盘',icon:History}] as const;
type Page=typeof nav[number]['id'];
export default function InternationalApp({active,onSwitch,sound,setSound}:{active:boolean;onSwitch:()=>void;sound:boolean;setSound:(v:boolean)=>void}){
const [page,setPage]=useState<Page>(()=>{const p=location.hash.split('/')[1];return nav.some(n=>n.id===p)?p as Page:'home'}),[menu,setMenu]=useState(false),[mode,setMode]=useState<'ai'|'local'>('ai'),[state,setState]=useState<GameState>({start:DEFAULT_POSITION,line:[]});
useEffect(()=>{const update=()=>{const p=location.hash.split('/')[1];if(location.hash.startsWith('#chess/')&&nav.some(n=>n.id===p))setPage(p as Page)};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[]);
function go(p:Page){setPage(p);location.hash='chess/'+p;setMenu(false);window.scrollTo({top:0});}
return <div className="app chess-app"><aside className={'sidebar '+(menu?'open':'')}><div className="brand"><span className="brand-seal chess-brand">♞</span><div>弈见<small>CELIA · CHESS</small></div></div><div className="side-caption">黑白之间，落子从容</div><nav aria-label="国际象棋导航">{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>go(n.id)}><n.icon size={19}/><span>{n.label}</span>{page===n.id&&<i/>}</button>)}</nav><div className="side-bottom"><div className="quote-mark">“</div><p>从第一步出发，<br/>看见更大的棋局。</p><span>弈见 · 国际象棋</span></div></aside><main><header><button className="mobile-menu" aria-label="打开国际象棋导航" onClick={()=>setMenu(s=>!s)}>{menu?<X/>:<Menu/>}</button><div className="breadcrumb">弈见 <span>/</span> {nav.find(n=>n.id===page)?.label}</div><div className="header-right"><span><i/> 黑白有度，落子有声</span><button aria-label={sound?'关闭落子音效':'开启落子音效'} aria-pressed={sound} onClick={()=>{setSoundEnabled(!sound);setSound(!sound);if(!sound)chessSound('place');}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></div></header><div className="content"><div className="variant-bar"><span><b>♞</b> 国际象棋 <small>CHESS</small></span><button onClick={onSwitch}><ArrowLeftRight size={16}/>切换到中国象棋</button></div>
{page==='home'?<><section className="chess-welcome"><div><div className="eyebrow"><span/> 一方新棋盘 · 一样的陪伴</div><h1>黑白之间，<br/><em>从容落子。</em></h1><p>从认识一枚兵，到读懂一盘棋。<br/>让每一次思考，都有温柔的回应。</p><div className="hero-actions"><button className="primary" onClick={()=>go('play')}>{state.line.length?'继续这一局':'开始第一局'}<ArrowRight size={17}/></button><button className="text-button" onClick={()=>go('learn')}>先认认棋子</button></div><div className="hero-note">八行八列 · 白方先行 · 零基础可玩</div></div><div className="chess-hero-board"><ChessBoard fen={DEFAULT_POSITION}/><span>六十四格，自有天地</span></div></section><div className="journey">{[{p:'learn' as Page,title:'从认识棋子开始',desc:'六种棋子，一点一点学。',icon:BookOpen},{p:'teaching' as Page,title:'摆一局，慢慢研究',desc:'自由摆局，锁定后听懂每一步。',icon:Lightbulb},{p:'puzzles' as Page,title:'解开一局的小巧思',desc:'10 道入门题，附逐步解析。',icon:Flag}].map((c,i)=><button className="journey-card" key={c.p} onClick={()=>go(c.p)}><span className="card-number">0{i+1}</span><span className="card-icon"><c.icon size={20}/></span><h3>{c.title}</h3><p>{c.desc}</p><div>开启练习<ArrowRight size={14}/></div></button>)}</div><div className="chess-home-note"><span>♔</span><p>将死赢棋，逼和则握手言和。<br/><small>国际象棋的马能跳子，兵直进斜吃。熟悉的棋院，新的探索。</small></p></div></>:<div className="page-title"><span className="eyebrow">弈见 · INTERNATIONAL CHESS</span><h1>{nav.find(n=>n.id===page)?.label}</h1><p>{{play:'白方先行。从绿色落点开始，慢慢建立自己的棋感。',learn:'先认棋子，再学特殊规则。每一课都可以亲手试一试。',teaching:'自由摆放，检查局面，再与本地 AI 一步步研究。',puzzles:'观察、尝试、回看答案。在小棋局里认识大思路。',review:'回看双方的每一次落子，让经验变成下一局的底气。'}[page]}</p></div>}
<div hidden={page!=='play'}><ChessMatch state={state} setState={setState} active={active&&page==='play'} mode={mode} setMode={setMode} onReview={()=>go('review')}/></div>
<div hidden={page!=='learn'}><ChessLearn/></div><div hidden={page!=='teaching'}><ChessTeaching active={active&&page==='teaching'}/></div><div hidden={page!=='puzzles'}><ChessPuzzles active={active&&page==='puzzles'}/></div><div hidden={page!=='review'}><ChessReview state={state} onPlay={()=>go('play')}/></div>
<InstallApp/><footer className="copyright-footer"><span>© 2026 Celia. 保留所有权利。</span><a href="/copyright.html" target="_blank" rel="noreferrer">版权声明</a><span>弈见 · 黑白之间</span></footer></div></main></div>;
}
