/* Copyright (c) 2026 Celia. All rights reserved. */
import type {Dispatch,SetStateAction} from 'react';
import {BookOpen,Swords,Flag,History,ArrowUpRight,ArrowRight,ChevronRight,Undo2,Lightbulb,RotateCcw,Check,ChevronLeft} from 'lucide-react';
import Board from '../components/Board';
import PageTitle from '../components/PageTitle';
import {names,reason,apply,lessons,type Piece,type Side,type Kind} from '../game/rules';
import type {Page,RecordStep} from '../types';
type Props={go:(p:Page)=>void;reset:(mode?:'ai'|'local',puzzle?:number|null)=>void;board:Piece[];selected:string|null;cell:(x:number,y:number)=>void;message:string;setKind:Dispatch<SetStateAction<Kind>>};
export default function HomePage({go,reset,board,selected,cell,message,setKind}:Props){return <><section className="welcome"><div><div className="eyebrow"><span/> 初入棋院 · 不负好时光</div><h1>棋逢初见，<br/>落子从容<span>。</span></h1><p>不懂规则也没关系。<br/>从第一步开始，让弈见陪你慢慢学会象棋。</p><div className="hero-actions"><button className="primary" onClick={()=>{reset();go('play')}}>开始第一局 <ArrowRight size={17}/></button><button className="text-button" onClick={()=>go('learn')}>先认识棋子 <ArrowUpRight size={16}/></button></div><div className="hero-note"><Check size={14}/> 零基础友好 <b>·</b> 随时悔棋 <b>·</b> 每步都有提示</div></div><div className="hero-art"><img src="/landscape.png" alt="宣纸上的远山、松枝与小羊"/><div className="art-caption">静 心<br/>观 棋</div><span className="art-seal">初见</span></div></section><div className="section-heading"><h2>今日，从这里开始</h2><span>不求一步登峰，只愿每日一进</span></div><section className="journey"><button className="journey-card" onClick={()=>go('learn')}><span className="card-icon"><BookOpen/></span><span className="card-number">01</span><h3>认棋 · 从零开始</h3><p>认识七种棋子，学会第一步</p><div><span>入门教学</span><ArrowUpRight size={18}/></div></button><button className="journey-card" onClick={()=>{reset();go('play')}}><span className="card-icon red-icon"><Swords/></span><span className="card-number">02</span><h3>对弈 · 温柔陪练</h3><p>有提示，能悔棋，放心落子</p><div><span>开始对局</span><ArrowUpRight size={18}/></div></button><button className="journey-card" onClick={()=>go('puzzles')}><span className="card-icon green-icon"><Flag/></span><span className="card-number">03</span><h3>破局 · 小试身手</h3><p>一局一小步，发现象棋的乐趣</p><div><span>残局闯关</span><ArrowUpRight size={18}/></div></button></section><section className="lower-grid"><div className="try-panel"><div className="section-heading"><h2>落一子，试试看</h2><span className="pill">新手体验</span></div><div className="try-inner"><div className="mini-board"><Board board={board} selected={selected} onCell={cell} compact/></div><div className="try-copy"><span className="small-label">棋盘上的第一课</span><h3>千里之行，<br/>始于一子。</h3><p>{message}</p><button className="text-button" onClick={()=>go('play')}>进入完整棋盘 <ArrowRight size={16}/></button></div></div></div><div className="daily"><div className="section-heading"><h2><Lightbulb size={18}/> 棋间小识</h2><span>每日一则</span></div><div className="daily-piece">马</div><h3>马走日，象走田</h3><p>马走“日”字，相走“田”字。<br/>记住这句小口诀，<br/>你就已经认识了两位新朋友。</p><button className="text-button" onClick={()=>{setKind('n');go('learn')}}>去学学怎么走 <ChevronRight size={15}/></button></div></section></>}
