/* Copyright (c) 2026 Celia. All rights reserved. */
import type {Dispatch,SetStateAction} from 'react';
import {BookOpen,Swords,Flag,History,ArrowUpRight,ArrowRight,ChevronRight,Undo2,Lightbulb,RotateCcw,Check,ChevronLeft} from 'lucide-react';
import Board from '../components/Board';
import PageTitle from '../components/PageTitle';
import {names,reason,apply,lessons,type Piece,type Side,type Kind} from '../game/rules';
import type {Page,RecordStep} from '../types';
type Props={kind:Kind;setKind:Dispatch<SetStateAction<Kind>>;setLessonPos:Dispatch<SetStateAction<Piece[]|null>>;setMessage:Dispatch<SetStateAction<string>>;completed:Kind[];lessonPos:Piece[]|null;demoBoard:Piece[];message:string;setCompleted:Dispatch<SetStateAction<Kind[]>>};
export default function LearnPage({kind,setKind,setLessonPos,setMessage,completed,lessonPos,demoBoard,message,setCompleted}:Props){return <><PageTitle tag="入门教学 · 认识新朋友" title="七种棋子，各有天地。" description="先认识它，再亲手走一步。象棋可以很简单。"/><div className="lesson-tabs">{(Object.keys(lessons) as Kind[]).map(k=><button className={kind===k?'active':''} onClick={()=>{setKind(k);setLessonPos(null);setMessage(lessons[k].rule)}} key={k}>{names.red[k]}{completed.includes(k)&&<Check size={12}/>}</button>)}</div><div className="play-layout"><div className="game-panel"><Board board={lessonPos||demoBoard} selected="lesson" onCell={(x,y)=>{const b=lessonPos||demoBoard,p=b.find(p=>p.id==='lesson')!;const err=reason(b,p,x,y);if(err)setMessage(err);else {setLessonPos(apply(b,{id:p.id,x,y}));setMessage('走对啦！你已经掌握了这个棋子的基本走法。');setCompleted(s=>Array.from(new Set([...s,kind])));}}}/></div><div className="info-card lesson-copy"><span className="small-label">棋子小课堂 / {completed.length} / 7 已练习</span><h2>{lessons[kind].title}</h2><p>{lessons[kind].rule}</p><div className="coach"><Lightbulb/><p>{lessons[kind].tip}</p></div><p aria-live="polite">{message}</p><button className="outline" onClick={()=>{setLessonPos(null);setMessage('点击绿色落点，亲手试一试。')}}>重置练习</button><div className="rule-note"><h3>怎样才算赢？</h3><p>当对方的帅被攻击，而且无论怎么走都无法解救，就叫“将杀”。对方没有合法的棋可以走，也算输。红方先行，双方轮流走一步。</p></div></div></div></>}
