/* Copyright (c) 2026 Celia. All rights reserved. */
import type {Dispatch,SetStateAction} from 'react';
import {BookOpen,Swords,Flag,History,ArrowUpRight,ArrowRight,ChevronRight,Undo2,Lightbulb,RotateCcw,Check,ChevronLeft} from 'lucide-react';
import Board from '../components/Board';
import PageTitle from '../components/PageTitle';
import {names,reason,apply,lessons,type Piece,type Side,type Kind} from '../game/rules';
import type {Page,RecordStep} from '../types';
type Props={puzzle:number|null;puzzles:{name:string;desc:string;board:Piece[]}[];mode:'ai'|'local';board:Piece[];selected:string|null;cell:(x:number,y:number)=>void;current:RecordStep;undo:()=>void;steps:RecordStep[];hint:()=>void;ended:string;turn:Side;reset:(mode?:'ai'|'local',puzzle?:number|null)=>void;message:string;go:(p:Page)=>void};
export default function PlayPage({puzzle,puzzles,mode,board,selected,cell,current,undo,steps,hint,ended,turn,reset,message,go}:Props){return <><PageTitle tag="对弈之间 · 慢慢成长" title={puzzle===null?'落子有声，学棋有伴。':puzzles[puzzle].name} description={puzzle===null?'输赢不着急，先走好眼前的这一步。':puzzles[puzzle].desc}/><div className="play-layout"><section className="game-panel"><div className="game-heading"><div><span className="status-dot"/> {mode==='ai'?'弈见 · 新手陪练':'本地双人 · 黑方'}</div><span>执黑 · 后手</span></div><Board board={board} selected={selected} onCell={cell} last={current.last}/><div className="game-heading"><strong className="red-text">{mode==='ai'?'初见棋友':'本地双人 · 红方'}</strong><span>执红 · 先手</span></div><div className="board-toolbar"><button onClick={undo} disabled={steps.length===1}><Undo2 size={17}/>悔棋</button><button onClick={hint} disabled={!!ended||turn==='black'&&mode==='ai'}><Lightbulb size={17}/>提示</button><button onClick={()=>reset(mode,puzzle)}><RotateCcw size={17}/>重新开始</button></div></section><aside className="play-info"><div className="info-card"><h3>这一局，慢慢来</h3><div className="mode-options"><button className={mode==='ai'?'chosen':''} onClick={()=>reset('ai')}>弈见陪练</button><button className={mode==='local'?'chosen':''} onClick={()=>reset('local')}>本地双人</button></div><p>当前：{ended||`${turn==='red'?'红':'黑'}方行棋`}</p><div className="coach" aria-live="polite"><span className="coach-badge">羊</span><div><strong>弈见说</strong><p>{message}</p></div></div><p className="muted">点击己方棋子查看合法落点。点击目标位置落子；吃子时，直接点击对方棋子。</p></div><div className="info-card"><h3>落子记录 <small>{steps.length-1} 步</small></h3><ol className="move-list">{steps.slice(1).map((s,i)=><li key={i}>{s.label}</li>)}</ol>{steps.length===1&&<p className="muted">棋盘已备好，等你落下第一子。</p>}<button className="outline full" onClick={()=>go('review')}>回看这一局 <History size={16}/></button></div></aside></div></>}
