/* Copyright (c) 2026 Celia. All rights reserved. */
import type {Dispatch,SetStateAction} from 'react';
import {BookOpen,Swords,Flag,History,ArrowUpRight,ArrowRight,ChevronRight,Undo2,Lightbulb,RotateCcw,Check,ChevronLeft} from 'lucide-react';
import Board from '../components/Board';
import PageTitle from '../components/PageTitle';
import {names,reason,apply,lessons,type Piece,type Side,type Kind} from '../game/rules';
import type {Page,RecordStep} from '../types';
type Props={steps:RecordStep[];reset:(mode?:'ai'|'local',puzzle?:number|null)=>void;go:(p:Page)=>void;review:number;setReview:Dispatch<SetStateAction<number>>};
export default function ReviewPage({steps,reset,go,review,setReview}:Props){return <><PageTitle tag="对局复盘 · 回望每一步" title="走过的每一步，都有收获。" description="回到刚才的棋局，看看每一枚棋子如何来到这里。"/>{steps.length===1?<div className="empty-state"><History size={40}/><h2>还没有落子记录</h2><p>先下一局棋，弈见会在这里陪你回顾。</p><button className="primary" onClick={()=>{reset();go('play')}}>去下一局 <ArrowRight size={16}/></button></div>:<div className="play-layout"><div className="game-panel"><Board board={steps[Math.min(review,steps.length-1)].board} last={steps[review]?.last}/><div className="review-controls"><button className="outline" disabled={review===0} onClick={()=>setReview(r=>r-1)}><ChevronLeft/>上一步</button><span>{review} / {steps.length-1}</span><button className="outline" disabled={review===steps.length-1} onClick={()=>setReview(r=>r+1)}>下一步<ChevronRight/></button></div><input aria-label="选择复盘步数" type="range" min="0" max={steps.length-1} value={review} onChange={e=>setReview(+e.target.value)}/></div><div className="info-card"><h3>{steps[review]?.label}</h3><p>红方棋子 {steps[review]?.board.filter(p=>p.side==='red').length} 枚 · 黑方棋子 {steps[review]?.board.filter(p=>p.side==='black').length} 枚</p><div className="coach"><Lightbulb/><p>{review===0?'开局先出动大子，让马、车有更多活动空间。':steps[review]?.label.includes('吃')?'这里发生了一次吃子。想一想：吃子之后，自己的棋子是否也会受到攻击？':'观察这步棋之后，有哪些线路被打开？下一步也要留意对方的威胁。'}</p></div><div className="review-list">{steps.map((s,i)=><button key={i} className={review===i?'active':''} onClick={()=>setReview(i)}>{i}. {s.label}</button>)}</div></div></div>}</>}
