/* Copyright (c) 2026 Celia. All rights reserved. */
import {useEffect,useState} from 'react';
import {Download,RefreshCw,X} from 'lucide-react';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function InstallApp(){
 const [prompt,setPrompt]=useState<InstallEvent|null>(null),[help,setHelp]=useState(false),[installed,setInstalled]=useState(false),[update,setUpdate]=useState<ServiceWorkerRegistration|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{setInstalled(matchMedia('(display-mode: standalone)').matches);const ready=(event:Event)=>{event.preventDefault();setPrompt(event as InstallEvent)};const done=()=>{setInstalled(true);setPrompt(null);setHelp(false)};const available=(event:Event)=>setUpdate((event as CustomEvent<ServiceWorkerRegistration>).detail);window.addEventListener('beforeinstallprompt',ready);window.addEventListener('appinstalled',done);window.addEventListener('yijian-update',available);return()=>{window.removeEventListener('beforeinstallprompt',ready);window.removeEventListener('appinstalled',done);window.removeEventListener('yijian-update',available)};},[]);
 async function install(){if(!prompt){setHelp(!help);return;}try{await prompt.prompt();const choice=await prompt.userChoice;setPrompt(null);setMessage(choice.outcome==='accepted'?'已提交安装，请查看设备桌面。':'已取消安装，网页版可以继续使用。');}catch{setPrompt(null);setHelp(true);}}
 return <div className="install-area">{!installed&&<button className="install-button" onClick={install}><Download size={15}/>安装弈见</button>}{update&&<button className="install-button" onClick={()=>{if(!update.waiting)return;setMessage('正在更新…');navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});update.waiting.postMessage({type:'ACTIVATE_UPDATE'});}}><RefreshCw size={15}/>更新到新版</button>}{message&&<span role="status">{message}</span>}{help&&<section className="install-help"><button className="close-help" onClick={()=>setHelp(false)} aria-label="关闭安装说明"><X size={18}/></button><h3>把弈见放到桌面</h3><p><strong>电脑：</strong>用 Chrome 或 Edge 打开网站，在地址栏或浏览器菜单中选择“安装弈见”或“将此网站安装为应用”。</p><p><strong>安卓：</strong>用 Chrome 打开，在菜单中选择“安装应用”或“添加到主屏幕”。</p><p><strong>iPhone / iPad：</strong>用 Safari 打开，点“分享”→“添加到主屏幕”，如有“作为网页 App 打开”选项，请开启。</p><p>安装后首次联网打开并完成资源缓存，即可离线使用核心棋局功能。棋局记录仍只保留在当前运行会话。</p><a href="/install.html" target="_blank" rel="noreferrer">查看完整安装说明 ↗</a></section>}</div>;
}
